Rol.create(cargo: 'Profesor jefe')
Rol.create(cargo: 'Asistente de aula')
Rol.create(cargo: 'Apoderado')
Rol.create(cargo: 'Asistente social')
Rol.create(cargo: 'UTP')
Rol.create(cargo: 'Directiva')
Rol.create(cargo: 'Convivencia escolar')
Rol.create(cargo: 'Psicólogo')
